### ISSUE TITLE
Needs more numbers

### ISSUE THREAD

**Issue by DVG** [ChrisBarthol/here-are-some-numbers#1]
Presently, the only numbers in the project are in the package.json files: https://github.com/ChrisBarthol/here-are-some-numbers/blob/master/elm-package.json, https://github.com/ChrisBarthol/here-are-some-numbers/blob/master/package.json

The [executable code](https://github.com/ChrisBarthol/here-are-some-numbers/blob/master/Hello.elm) has no numbers whatsoever!

**Comment by ChrisBarthol** [comment]
+1 

This is a major blocker.

**Comment by ChrisBarthol** [comment]
commit #bf69b53 Should take care of this issue.

**Comment by ChrisBarthol** [comment]
There are now more numbers than ever before!
